// <auto-generated />
#nullable enable

using System.Runtime.CompilerServices;
using NativeMedia.Avalonia.Linux;
using NativeMedia.Avalonia.Windows;
using NativeMedia.Avalonia.macOS;

namespace NativeMedia.Avalonia.Generated;

/// <summary>
/// Registers the platform backend before application code creates a media
/// control. This file is injected by the NuGet buildTransitive assets so the
/// references remain visible to the NativeAOT compiler.
/// </summary>
internal static class NativeMediaAutoRegistration
{
    [ModuleInitializer]
    internal static void Initialize()
    {
        if (global::System.OperatingSystem.IsWindows())
            WindowsMediaFoundation.Use();
        else if (global::System.OperatingSystem.IsLinux())
            LinuxFfmpeg.Use();
        else if (global::System.OperatingSystem.IsMacOS())
            MacAvFoundation.Use();
    }
}
